{"name": "Тест создания двух одинаковых курьеров", "status": "failed", "statusDetails": {"message": "AssertionError: assert (409 == 409 and {'code': 409,...уйте другой.'} == {'message': '...используется'}\n +  where 409 = <Response [409]>.status_code\n  \n  Differing items:\n  \u001b[0m{\u001b[33m'\u001b[39;49;00m\u001b[33mmessage\u001b[39;49;00m\u001b[33m'\u001b[39;49;00m: \u001b[33m'\u001b[39;49;00m\u001b[33mЭтот логин уже используется. Попробуйте другой.\u001b[39;49;00m\u001b[33m'\u001b[39;49;00m}\u001b[90m\u001b[39;49;00m != \u001b[0m{\u001b[33m'\u001b[39;49;00m\u001b[33mmessage\u001b[39;49;00m\u001b[33m'\u001b[39;49;00m: \u001b[33m'\u001b[39;49;00m\u001b[33mЭтот логин уже используется\u001b[39;49;00m\u001b[33m'\u001b[39;49;00m}\u001b[90m\u001b[39;49;00m\n  Left contains 1 more item:\n  \u001b[0m{\u001b[33m'\u001b[39;49;00m\u001b[33mcode\u001b[39;49;00m\u001b[33m'\u001b[39;49;00m: \u001b[94m409\u001b[39;49;00m}\u001b[90m\u001b[39;49;00m\n  Use -v to get more diff)", "trace": "self = <tests.test_create_courier.TestCreateCourier object at 0x00000183D13291D0>\n\n    @allure.title('Тест создания двух одинаковых курьеров')\n    def test_create_duplicate_courier_false(self):\n        courier_payload = register_new_courier_and_return_login_password() # Данные для курьера\n        requests.post(URLs.URL_CREATE_COURIER, data = courier_payload) # Создаем курьера1\n        response_second = requests.post(URLs.URL_CREATE_COURIER, data = courier_payload) # Создаем курьера2 и читаем ответ\n>       assert (response_second.status_code == 409 and\n                response_second.json() == TestData.Message_Courier_Conflict) # проверяем, что запрос возвращает правильный код ответа и текст сообщения\nE       AssertionError: assert (409 == 409 and {'code': 409,...уйте другой.'} == {'message': '...используется'}\nE        +  where 409 = <Response [409]>.status_code\nE         \nE         Differing items:\nE         \u001b[0m{\u001b[33m'\u001b[39;49;00m\u001b[33mmessage\u001b[39;49;00m\u001b[33m'\u001b[39;49;00m: \u001b[33m'\u001b[39;49;00m\u001b[33mЭтот логин уже используется. Попробуйте другой.\u001b[39;49;00m\u001b[33m'\u001b[39;49;00m}\u001b[90m\u001b[39;49;00m != \u001b[0m{\u001b[33m'\u001b[39;49;00m\u001b[33mmessage\u001b[39;49;00m\u001b[33m'\u001b[39;49;00m: \u001b[33m'\u001b[39;49;00m\u001b[33mЭтот логин уже используется\u001b[39;49;00m\u001b[33m'\u001b[39;49;00m}\u001b[90m\u001b[39;49;00m\nE         Left contains 1 more item:\nE         \u001b[0m{\u001b[33m'\u001b[39;49;00m\u001b[33mcode\u001b[39;49;00m\u001b[33m'\u001b[39;49;00m: \u001b[94m409\u001b[39;49;00m}\u001b[90m\u001b[39;49;00m\nE         Use -v to get more diff)\n\ntests\\test_create_courier.py:24: AssertionError"}, "start": 1758455985584, "stop": 1758455986747, "uuid": "3ffcffda-8da4-4068-89ce-093b8dc4ca6c", "historyId": "40e9ecc9a5f744043ddebc617a5f4e51", "testCaseId": "40e9ecc9a5f744043ddebc617a5f4e51", "fullName": "tests.test_create_courier.TestCreateCourier#test_create_duplicate_courier_false", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_courier"}, {"name": "subSuite", "value": "TestCreateCourier"}, {"name": "host", "value": "DeMaNs"}, {"name": "thread", "value": "73352-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_courier"}], "titlePath": ["tests", "test_create_courier.py", "TestCreateCourier"]}